version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cure_app
    volumes:
      - '.:/var/www/html'
    working_dir: /var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=national_medical_exam
      - DB_USERNAME=wassem
      - DB_PASSWORD=password
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy  # Wait until the DB is ready

  web:
    image: 'nginx:alpine'
    container_name: laravel_web
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: 'mysql:5.7'
    container_name: cure_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: national_medical_exam
      MYSQL_USER: wassem
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - laravel
    healthcheck:  # Ensure DB is ready before starting app
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 5s

volumes:
  db_data:

networks:
  laravel:
