version: '3.8'
services:
  app:
    image: php:8.1-fpm  # Adjust PHP version to match your project
    container_name: cure_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=national_medical_exam
      - DB_USERNAME=root
      - DB_PASSWORD=

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0  # Adjust MySQL version as needed
    container_name: cure_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: national_medical_exam
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
